export const mockRescueCases = [
  {
    id: '1',
    title: 'Injured Street Dog',
    description: 'Dog with severe leg injury found near Mohakhali bus stand',
    status: 'inProgress',
    severity: 'emergency',
    location: { lat: 23.7831, lng: 90.4048, address: 'Mohakhali, Dhaka' },
    image: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=400',
    reportedBy: 'Rahim Ahmed',
    assignedTo: 'Volunteer Team A',
    createdAt: new Date('2024-06-01T10:30:00'),
    updatedAt: new Date('2024-06-01T11:00:00'),
    aiSeverityScore: 0.87,
  },
  {
    id: '2',
    title: 'Abandoned Kittens',
    description: 'Three kittens abandoned in a box near Dhanmondi lake',
    status: 'pending',
    severity: 'moderate',
    location: { lat: 23.7461, lng: 90.3742, address: 'Dhanmondi, Dhaka' },
    image: 'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=400',
    reportedBy: 'Fatema Begum',
    assignedTo: null,
    createdAt: new Date('2024-06-01T09:00:00'),
    updatedAt: new Date('2024-06-01T09:00:00'),
    aiSeverityScore: 0.42,
  },
  {
    id: '3',
    title: 'Malnourished Cat',
    description: 'Extremely thin cat found at Gulshan 2 circle',
    status: 'accepted',
    severity: 'moderate',
    location: { lat: 23.7935, lng: 90.4147, address: 'Gulshan 2, Dhaka' },
    image: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=400',
    reportedBy: 'Karim Hassan',
    assignedTo: 'Dr. Sumaiya Akter',
    createdAt: new Date('2024-06-01T08:00:00'),
    updatedAt: new Date('2024-06-01T08:30:00'),
    aiSeverityScore: 0.55,
  },
  {
    id: '4',
    title: 'Bird with Broken Wing',
    description: 'Parrot with broken wing found in Banani residential area',
    status: 'completed',
    severity: 'safe',
    location: { lat: 23.7934, lng: 90.4043, address: 'Banani, Dhaka' },
    image: 'https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=400',
    reportedBy: 'Nusrat Jahan',
    assignedTo: 'Dr. Rahman',
    createdAt: new Date('2024-05-31T14:00:00'),
    updatedAt: new Date('2024-05-31T16:00:00'),
    aiSeverityScore: 0.3,
  },
];

export const mockAnimalsForAdoption = [
  {
    id: '1',
    name: 'Luna',
    species: 'Dog',
    breed: 'Mixed Breed',
    age: '2 years',
    gender: 'Female',
    color: 'Golden Brown',
    image: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=400',
    health: { vaccinated: true, neutered: true, dewormed: true, microchipped: false },
    behavior: ['Friendly', 'Playful', 'Good with kids'],
    description: 'Luna is a gentle, loving dog rescued from the streets of Mirpur. She gets along well with children and other pets.',
    location: 'Mirpur, Dhaka',
    shelter: 'PawSphere Shelter Dhaka',
    matchScore: 95,
    adoptionFee: 0,
    postedAt: new Date('2024-05-20'),
  },
  {
    id: '2',
    name: 'Mochi',
    species: 'Cat',
    breed: 'Persian Mix',
    age: '1 year',
    gender: 'Male',
    color: 'White & Orange',
    image: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=400',
    health: { vaccinated: true, neutered: false, dewormed: true, microchipped: false },
    behavior: ['Calm', 'Affectionate', 'Indoor cat'],
    description: 'Mochi is a beautiful Persian mix who loves cuddles and quiet environments. Perfect for apartment living.',
    location: 'Gulshan, Dhaka',
    shelter: 'Feline Friends BD',
    matchScore: 88,
    adoptionFee: 0,
    postedAt: new Date('2024-05-22'),
  },
  {
    id: '3',
    name: 'Rocky',
    species: 'Dog',
    breed: 'Labrador Mix',
    age: '3 years',
    gender: 'Male',
    color: 'Black',
    image: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=400',
    health: { vaccinated: true, neutered: true, dewormed: true, microchipped: true },
    behavior: ['Energetic', 'Loyal', 'Needs exercise'],
    description: 'Rocky is a strong and loyal Labrador mix. He needs an active family with a yard. Excellent guard dog.',
    location: 'Uttara, Dhaka',
    shelter: 'Happy Paws NGO',
    matchScore: 72,
    adoptionFee: 0,
    postedAt: new Date('2024-05-18'),
  },
  {
    id: '4',
    name: 'Biscuit',
    species: 'Cat',
    breed: 'Domestic Shorthair',
    age: '6 months',
    gender: 'Female',
    color: 'Tabby',
    image: 'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=400',
    health: { vaccinated: true, neutered: false, dewormed: true, microchipped: false },
    behavior: ['Playful', 'Curious', 'Kitten energy'],
    description: 'Biscuit is an adorable tabby kitten full of energy and curiosity. She was found abandoned in Dhanmondi.',
    location: 'Dhanmondi, Dhaka',
    shelter: 'Kitty Rescue BD',
    matchScore: 91,
    adoptionFee: 0,
    postedAt: new Date('2024-05-25'),
  },
  {
    id: '5',
    name: 'Polly',
    species: 'Bird',
    breed: 'Parakeet',
    age: '1 year',
    gender: 'Female',
    color: 'Green & Yellow',
    image: 'https://images.unsplash.com/photo-1552728089-57bdde30beb3?w=400',
    health: { vaccinated: false, neutered: false, dewormed: false, microchipped: false },
    behavior: ['Vocal', 'Social', 'Friendly'],
    description: 'Polly is a cheerful parakeet who loves to sing and interact. Great for families and beginners.',
    location: 'Banani, Dhaka',
    shelter: 'Bird Sanctuary BD',
    matchScore: 79,
    adoptionFee: 0,
    postedAt: new Date('2024-05-28'),
  },
  {
    id: '6',
    name: 'Bruno',
    species: 'Dog',
    breed: 'German Shepherd Mix',
    age: '4 years',
    gender: 'Male',
    color: 'Black & Tan',
    image: 'https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?w=400',
    health: { vaccinated: true, neutered: true, dewormed: true, microchipped: true },
    behavior: ['Protective', 'Intelligent', 'Trainable'],
    description: 'Bruno is a highly intelligent shepherd mix who is already trained in basic commands. Perfect for experienced owners.',
    location: 'Mohammadpur, Dhaka',
    shelter: 'PawSphere Shelter Dhaka',
    matchScore: 83,
    adoptionFee: 0,
    postedAt: new Date('2024-05-15'),
  },
];

export const mockVets = [
  {
    id: '1',
    name: 'Dr. Sumaiya Akter',
    specialty: 'Small Animals & Surgery',
    hospital: 'Pet Care Clinic Dhaka',
    location: { lat: 23.7515, lng: 90.3756, address: 'Dhanmondi 15, Dhaka' },
    phone: '+880 1711-234567',
    email: 'dr.sumaiya@petcarebd.com',
    rating: 4.9,
    reviews: 127,
    experience: '12 years',
    services: ['Surgery', 'Vaccination', 'Dental', 'Emergency'],
    available: true,
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sumaiya',
    fee: 500,
    languages: ['Bangla', 'English'],
    verified: true,
    nextAvailable: '10:00 AM Today',
  },
  {
    id: '2',
    name: 'Dr. Karim Rahman',
    specialty: 'Large Animals & Wildlife',
    hospital: 'Dhaka Animal Hospital',
    location: { lat: 23.7935, lng: 90.4147, address: 'Gulshan 1, Dhaka' },
    phone: '+880 1712-345678',
    email: 'dr.karim@dhakavets.com',
    rating: 4.7,
    reviews: 89,
    experience: '8 years',
    services: ['General Practice', 'Vaccination', 'Nutrition', 'Behavior'],
    available: false,
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=karim',
    fee: 400,
    languages: ['Bangla', 'English'],
    verified: true,
    nextAvailable: '2:00 PM Today',
  },
  {
    id: '3',
    name: 'Dr. Priya Singh',
    specialty: 'Exotic Animals & Birds',
    hospital: 'PetLife Veterinary Center',
    location: { lat: 23.7831, lng: 90.4048, address: 'Mohakhali, Dhaka' },
    phone: '+880 1713-456789',
    email: 'dr.priya@petlifebd.com',
    rating: 4.8,
    reviews: 63,
    experience: '6 years',
    services: ['Bird Care', 'Reptiles', 'Exotic Pets', 'Wellness Check'],
    available: true,
    image: 'https://api.dicebear.com/7.x/avataaars/svg?seed=priya',
    fee: 600,
    languages: ['Bangla', 'English', 'Hindi'],
    verified: true,
    nextAvailable: 'Now Available',
  },
];

export const mockVolunteers = [
  {
    id: '1',
    name: 'Ahmed Hossain',
    skills: ['Rescuer', 'Transporter'],
    location: 'Mirpur, Dhaka',
    points: 1250,
    badges: ['topRescuer', 'animalHero'],
    rescues: 45,
    feedingRounds: 12,
    joinedAt: new Date('2023-01-15'),
    available: true,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ahmed',
    rating: 4.9,
  },
  {
    id: '2',
    name: 'Fatema Khatun',
    skills: ['Feeder', 'Vet Assistant'],
    location: 'Dhanmondi, Dhaka',
    points: 980,
    badges: ['feedingGuardian', 'vetHelper'],
    rescues: 18,
    feedingRounds: 67,
    joinedAt: new Date('2023-03-20'),
    available: true,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=fatema',
    rating: 4.8,
  },
  {
    id: '3',
    name: 'Rahim Chowdhury',
    skills: ['Rescuer', 'Feeder', 'Transporter'],
    location: 'Gulshan, Dhaka',
    points: 2100,
    badges: ['topRescuer', 'animalHero', 'donorChampion'],
    rescues: 87,
    feedingRounds: 34,
    joinedAt: new Date('2022-11-10'),
    available: false,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=rahim',
    rating: 5.0,
  },
];

export const mockDonations = {
  totalRaised: 485000,
  totalDonors: 1247,
  breakdown: [
    { category: 'Medical Treatment', amount: 195000, percentage: 40 },
    { category: 'Food & Nutrition', amount: 121250, percentage: 25 },
    { category: 'Shelter Maintenance', amount: 97000, percentage: 20 },
    { category: 'Ambulance Service', amount: 48500, percentage: 10 },
    { category: 'Equipment', amount: 24250, percentage: 5 },
  ],
  recentDonors: [
    { name: 'Anonymous', amount: 5000, date: new Date(), type: 'Medical' },
    { name: 'Rina Begum', amount: 2000, date: new Date(), type: 'Food' },
    { name: 'Tech for Animals', amount: 25000, date: new Date(), type: 'Shelter' },
  ],
};

export const mockCommunityPosts = [
  {
    id: '1',
    author: 'Nusrat Jahan',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=nusrat',
    type: 'successStory',
    title: 'Luna Found Her Forever Home! 🐾',
    content: 'After 3 months in our shelter, Luna has finally been adopted by a wonderful family in Gulshan. She now has a garden to play in and two kids who adore her. This is why we do what we do!',
    image: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600',
    likes: 234,
    comments: 47,
    shares: 89,
    createdAt: new Date('2024-06-01T08:00:00'),
    liked: false,
  },
  {
    id: '2',
    author: 'Mirpur Animal Watch',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=mirpur',
    type: 'lostPet',
    title: '🚨 LOST: Golden Retriever near Mirpur 10',
    content: 'LOST DOG: Golden Retriever, male, 3 years old, answers to "Buddy". Last seen near Mirpur 10 roundabout on June 1st. He has a blue collar. Please contact if found! Reward offered.',
    image: null,
    likes: 156,
    comments: 23,
    shares: 412,
    createdAt: new Date('2024-06-01T10:00:00'),
    liked: false,
  },
  {
    id: '3',
    author: 'PawSphere Team',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=pawsphere',
    type: 'helpNeeded',
    title: 'Urgent: 12 kittens need foster homes in Dhaka',
    content: 'Our shelter is at capacity! We have 12 beautiful kittens aged 6-10 weeks who urgently need foster families in the Dhaka area. Food and vet care covered by PawSphere. Can you help?',
    image: 'https://images.unsplash.com/photo-1574158622682-e40e69881006?w=600',
    likes: 445,
    comments: 167,
    shares: 523,
    createdAt: new Date('2024-05-31T15:00:00'),
    liked: true,
  },
];

export const mockLeaderboard = [
  { rank: 1, name: 'Rahim Chowdhury', points: 2100, badge: 'topRescuer', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=rahim' },
  { rank: 2, name: 'Ahmed Hossain', points: 1250, badge: 'animalHero', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ahmed' },
  { rank: 3, name: 'Fatema Khatun', points: 980, badge: 'feedingGuardian', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=fatema' },
  { rank: 4, name: 'Nusrat Jahan', points: 750, badge: 'animalHero', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=nusrat' },
  { rank: 5, name: 'Karim Hassan', points: 620, badge: 'donorChampion', avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=karim2' },
];

export const mockDashboardStats = {
  totalRescues: 1847,
  activeVolunteers: 342,
  totalDonations: 485000,
  pendingAdoptions: 28,
  rescueTrend: [
    { month: 'Jan', count: 89 },
    { month: 'Feb', count: 124 },
    { month: 'Mar', count: 156 },
    { month: 'Apr', count: 198 },
    { month: 'May', count: 231 },
    { month: 'Jun', count: 187 },
  ],
  animalTypes: [
    { type: 'Dogs', count: 892 },
    { type: 'Cats', count: 634 },
    { type: 'Birds', count: 187 },
    { type: 'Others', count: 134 },
  ],
};

export const mockMapMarkers = [
  { id: '1', type: 'rescue', severity: 'emergency', lat: 23.7831, lng: 90.4048, title: 'Injured Dog - Mohakhali' },
  { id: '2', type: 'rescue', severity: 'moderate', lat: 23.7461, lng: 90.3742, title: 'Abandoned Kittens - Dhanmondi' },
  { id: '3', type: 'shelter', severity: 'safe', lat: 23.7935, lng: 90.4147, title: 'PawSphere Shelter' },
  { id: '4', type: 'vet', severity: 'safe', lat: 23.7515, lng: 90.3756, title: 'Pet Care Clinic' },
  { id: '5', type: 'feeding', severity: 'safe', lat: 23.7600, lng: 90.3900, title: 'Feeding Zone A' },
  { id: '6', type: 'ambulance', severity: 'safe', lat: 23.7700, lng: 90.4100, title: 'Animal Ambulance Unit 1' },
];
